### ISSUE TITLE
dimension error with on-fly performance_schema

### ISSUE THREAD

**Issue by karelbarel** [box/Anemometer#120]
Fatal error: Uncaught exception 'Exception' with message 'No alias dimension' in anemometer/lib/MySQLTableReport.php:235 Stack trace:
#0 anemometer/lib/Anemometer.php(82): MySQLTableReport->get_table_by_alias('dimension')
#1 anemometer/lib/Anemometer.php(325): Anemometer->api()
#2 anemometer/index.php(42): Anemometer->report()
#3 {main} thrown in anemometer/lib/MySQLTableReport.php on line 235

by conf https://github.com/box/Anemometer/wiki/Using-PERFORMANCE_SCHEMA-in-MySQL-5.6
there is not dimension definition inside $conf['datasources']['mysql56']

workaround for me
vi +82 anemometer/lib/Anemometer.php
if ('performance_schema' != $this->data_model->get_source_type()) {
        $dimension_table = $this->report_obj->get_table_by_alias('dimension');
}

**Comment by grypyrg** [comment]
Exactly, I had the same.
